/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Color;
import java.io.File;

/**
 *
 * @author ALLAN
 */
public class FrmLogin extends javax.swing.JFrame {

    private Logica log;

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        log = new Logica();
    }

    public FrmLogin(Logica log) {
        initComponents();
        setLocationRelativeTo(null);
        this.log = log;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        lblRegistrar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(510, 760));
        setResizable(false);
        getContentPane().setLayout(null);

        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLogin.setText("Login");
        txtLogin.setBorder(null);
        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });
        txtLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLoginKeyReleased(evt);
            }
        });
        getContentPane().add(txtLogin);
        txtLogin.setBounds(140, 260, 280, 40);

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassword.setText("Password");
        txtPassword.setToolTipText("Password");
        txtPassword.setBorder(null);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(140, 380, 290, 30);

        btnAceptar.setBackground(new java.awt.Color(242, 100, 34));
        btnAceptar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Sign in");
        btnAceptar.setBorder(null);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(80, 510, 360, 90);

        lblRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblRegistrar.setText("Registrar    ");
        lblRegistrar.setOpaque(true);
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseExited(evt);
            }
        });
        getContentPane().add(lblRegistrar);
        lblRegistrar.setBounds(280, 440, 160, 20);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(370, 460, 55, 2);

        jLabel3.setBackground(new java.awt.Color(28, 58, 77));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("APP PRO");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 20, 180, 40);
        getContentPane().add(lblFoto);
        lblFoto.setBounds(210, 110, 120, 95);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLoginKeyReleased
        try {
            File f = new File(txtLogin.getText().trim() + ".jpg");
            if (f.exists() && !f.isDirectory()) {
                Util.loadImage(txtLogin.getText().trim() + ".jpg", lblFoto);
            } else {
                lblFoto.setIcon(null);
            }
        } catch (Exception ex) {
            System.out.println("Algo paso!!!!");
        }
    }//GEN-LAST:event_txtLoginKeyReleased

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        Usuario user = log.verificarUsuario(txtLogin.getText().trim(), new String(txtPassword.getPassword()));
        if (user != null) {
            FrmPrincipal frm = new FrmPrincipal(log, user);
            frm.setVisible(true);
            dispose();//Se destruye el login 
        } else {
            System.out.println("No entro!!");
        }

        String password = new String(txtPassword.getPassword());
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered
        lblRegistrar.setForeground(Color.BLUE);
        jSeparator1.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void lblRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseExited
        lblRegistrar.setForeground(Color.BLACK);
        jSeparator1.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblRegistrarMouseExited

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        FrmUsuario frm = new FrmUsuario(log);
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
